# Generated by Django 5.1.4 on 2025-01-21 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered')], default='Created', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Rice and Pasta', 'Rice and Pasta'), ('Processed Proteins', 'Processed Proteins'), ('Canned Food', 'Canned Food'), ('Drinks and Desserts', 'Drinks and Desserts'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('care_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_package_items', to='api.carepackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='carepackage',
            name='items',
            field=models.ManyToManyField(through='api.CarePackageItem', to='api.inventory'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered')], default='Ordered', max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_histories', to='api.carepackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
