# Generated by Django 5.1.4 on 2024-12-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_delivered', models.PositiveIntegerField()),
                ('quantity_on_change', models.IntegerField()),
                ('category', models.CharField(choices=[('Rice and Pasta', 'Rice and Pasta'), ('Processed Proteins', 'Processed Proteins'), ('Canned Food', 'Canned Food'), ('Drinks and Desserts', 'Drinks and Desserts'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
