# Generated by Django 5.1.4 on 2025-01-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carepackage',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered'), ('Out of Stock', 'Out of Stock')], default='Created', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered'), ('Out of Stock', 'Out of Stock')], default='Ordered', max_length=50),
        ),
    ]
