# Generated by Django 5.1.4 on 2025-01-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='Created', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('care_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_package_items', to='api.carepackage')),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='carepackageitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory'),
        ),
        migrations.AddField(
            model_name='carepackage',
            name='items',
            field=models.ManyToManyField(through='api.CarePackageItem', to='api.inventory'),
        ),
    ]
