# Generated by Django 5.1.4 on 2025-01-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carepackage',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
