# Generated by Django 5.1.4 on 2024-12-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_delivered',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_on_change',
        ),
    ]
