# Generated by Django 5.1.4 on 2025-01-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carepackage_carepackageitem_delete_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carepackage',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carepackageitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
