# Generated by Django 5.1.4 on 2024-12-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_id',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
