# Generated by Django 5.1.4 on 2025-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_carepackage_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carepackage',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
