# Generated by Django 5.1.4 on 2025-01-14 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_package_alter_inventory_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered')], default='Ordered', max_length=50)),
            ],
        ),

        migrations.AlterField(
            model_name='carepackage',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered')], default='Created', max_length=50),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_histories', to='api.carepackage'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
