# Generated by Django 5.1.4 on 2025-01-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderhistory_delete_package_alter_carepackage_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
