# Generated by Django 5.1.4 on 2025-01-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_inventory_quantity_delivered_and_more'),
        ('api', '0005_inventory'),
    ]

    operations = [
    ]
