# Generated by Django 5.1.4 on 2025-01-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250102_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True, help_text='The date the package was created.')),
                ('pickup_location', models.CharField(help_text='The location where the package can be picked up.', max_length=255)),
                ('contents', models.JSONField(help_text='A list of products the package will contain.')),
            ],
        ),
    ]
